### ISSUE TITLE
USPS Address Parsing

### ISSUE THREAD

**Issue by Jaegermeiste** [soenneker/soenneker.utils.dtos.streetaddress#208]
Parse/TryParse does not handle the third line very well for USPS formatted addresses.

The function assumes all tokens are comma separated, but the USPS assumes all punctuation may be omitted ([https://pe.usps.com/text/pub28/pub28apa_002.htm](https://pe.usps.com/text/pub28/pub28apa_002.htm)). "all punctuation may be omitted" This becomes a problem for the last line in particular, where three tokens are space-delimited.

Some Guy
123 Street Address
Option Street 2
City ST 12345-9876
USA

Also, the parser should probably handle \n as a split token as well as comma.

**Comment by soenneker** [comment]
@Jaegermeiste can you verify this has been fixed? Thanks
